fix:NameError - undefined local variable or method `current_page'
When pagination is required to display the delayed jobs, an error occurs
when attempting to render `_next_more.erb` as the `current_page` variable
is not defined.

```
NameError - undefined local variable or method `current_page'
```

Replacing `current_page` with `request.path`

Tested with:
  resque (1.25.2)
  resque-scheduler (4.0.0)
  resque-web (0.0.6)